/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package konversisuhu;

/**
 *
 * @author Nabila
 */
public class fHome extends javax.swing.JFrame {

    /**
     * Creates new form fHome
     */
    public fHome() {
        initComponents();
        tOutput.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        labelAwal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tSuhuAsal = new javax.swing.JTextField();
        cSkalaAsal = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cSkalaTujuan = new javax.swing.JComboBox<>();
        tHasilKonversi = new javax.swing.JPanel();
        tOutput = new javax.swing.JLabel();
        bKonversi = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAwal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelAwal.setForeground(new java.awt.Color(102, 102, 255));
        labelAwal.setText("Aplikasi Konversi Suhu");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Suhu Asal"));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        tSuhuAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSuhuAsalActionPerformed(evt);
            }
        });

        cSkalaAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Farhenheit", "Kelvin" }));
        cSkalaAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSkalaAsalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cSkalaAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSuhuAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tSuhuAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cSkalaAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Suhu Tujuan"));

        cSkalaTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Farhenhet", "Kelvin" }));
        cSkalaTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSkalaTujuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cSkalaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cSkalaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tHasilKonversi.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Konversi"));

        tOutput.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        javax.swing.GroupLayout tHasilKonversiLayout = new javax.swing.GroupLayout(tHasilKonversi);
        tHasilKonversi.setLayout(tHasilKonversiLayout);
        tHasilKonversiLayout.setHorizontalGroup(
            tHasilKonversiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tHasilKonversiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tHasilKonversiLayout.setVerticalGroup(
            tHasilKonversiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tHasilKonversiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        bKonversi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bKonversi.setForeground(new java.awt.Color(153, 153, 153));
        bKonversi.setIcon(new javax.swing.ImageIcon("C:\\Users\\X1 Tab G3\\Downloads\\icons8-calculate-20.png")); // NOI18N
        bKonversi.setText("Konversi");
        bKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKonversiActionPerformed(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(0, 153, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/konversisuhu/icons8-reset-18.png"))); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bTutup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bTutup.setForeground(new java.awt.Color(255, 51, 51));
        bTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/konversisuhu/icons8-close-20.png"))); // NOI18N
        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tHasilKonversi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bKonversi)
                .addGap(18, 18, 18)
                .addComponent(bReset)
                .addGap(18, 18, 18)
                .addComponent(bTutup)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(labelAwal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelAwal)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tHasilKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKonversi)
                    .addComponent(bReset)
                    .addComponent(bTutup))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tSuhuAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSuhuAsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSuhuAsalActionPerformed
    
    private void cSkalaAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSkalaAsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSkalaAsalActionPerformed

    private void cSkalaTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSkalaTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSkalaTujuanActionPerformed

    private void bKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKonversiActionPerformed
        // TODO add your handling code here:
        double suhuAsal, output;
        String skalaAsal, skalaTujuan;

        suhuAsal = Double.parseDouble(tSuhuAsal.getText());
        skalaAsal = cSkalaAsal.getSelectedItem().toString();
        skalaTujuan = cSkalaTujuan.getSelectedItem().toString();

        if (skalaAsal.equals("Celcius") && skalaTujuan.equals("Celcius")) {
            output = suhuAsal;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Celcius") && skalaTujuan.equals("Fahrenheit")) {
            output = (suhuAsal * 9 / 5) + 32;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Celcius") && skalaTujuan.equals("Kelvin")) {
            output = suhuAsal + 273.15;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Fahrenheit") && skalaTujuan.equals("Fahrenheit")) {
            output = suhuAsal;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Fahrenheit") && skalaTujuan.equals("Celcius")) {
            output = (suhuAsal - 32) * 5 / 9;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Fahrenheit") && skalaTujuan.equals("Kelvin")) {
            output = (suhuAsal - 32) * 5 / 9 + 273.15;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Kelvin") && skalaTujuan.equals("Kelvin")) {
            output = suhuAsal;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Kelvin") && skalaTujuan.equals("Celcius")) {
            output = suhuAsal - 273.15;
            tOutput.setText(String.valueOf(output));
        } else if (skalaAsal.equals("Kelvin") && skalaTujuan.equals("Fahrenheit")) {
            output = (suhuAsal - 273.15) * 9 / 5 + 32;
            tOutput.setText(String.valueOf(output));
        } else {
            tOutput.setText("Skala tidak dikenali!");
        }
    }//GEN-LAST:event_bKonversiActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bResetActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKonversi;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTutup;
    private javax.swing.JComboBox<String> cSkalaAsal;
    private javax.swing.JComboBox<String> cSkalaTujuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAwal;
    private javax.swing.JPanel tHasilKonversi;
    private javax.swing.JLabel tOutput;
    private javax.swing.JTextField tSuhuAsal;
    // End of variables declaration//GEN-END:variables
}
